/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ball.glb 
Author: Rohit Pawar (https://sketchfab.com/rohit8999)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cricket-ball-sports-white-f7fb5ae0d11e4d37a2d9ebccfcba5592
Title: Cricket Ball (Sports) (White).
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ball.glb')
  return (
    <group {...props} dispose={null} scale={0.1}>
      <mesh geometry={nodes.Sphere_Material004_0.geometry} material={materials['Material.004']} rotation={[-2.713, 0, -0.398]}  />
      <mesh geometry={nodes.Cylinder002_Material002_0.geometry} material={materials['Material.002']} position={[80.777, 51.079, 23.637]} rotation={[-2.713, 0, -0.398]} />
    </group>
  )
}

useGLTF.preload('/ball.glb')
