/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to add physics, controls, scaling, and collider
*/

import { useRef } from 'react'
import { useGLTF, useKeyboardControls } from '@react-three/drei'
import { RigidBody, CuboidCollider } from '@react-three/rapier'
import { useFrame } from '@react-three/fiber'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bat.glb')
  const batRef = useRef()
  const [subscribeKeys, getKeys] = useKeyboardControls()

  useFrame(() => {
    const { forward, backward, left, right, shift } = getKeys()
    if (forward && shift) {
      batRef.current?.applyImpulse({ x: 0, y: 0.17, z: -0.01 })
      batRef.current?.addTorque({ x: 0.006, y: 0, z: 0 })
    } else if (right && shift) {
      batRef.current?.applyImpulse({ x: 0.0, y: 0.17, z: -0.017 })
      batRef.current?.addTorque({ x: 0, y: -0.01, z: 0 })
    } else if (left && shift) {
      batRef.current?.applyImpulse({ x: 0.0, y: 0.17, z: -0.017 })
      batRef.current?.addTorque({ x: 0, y: 0.01, z: 0 })
    }
    // backward+shift can be added later if needed
  })

  return (
    <RigidBody
      ref={batRef}
      type="dynamic"
      colliders={false}
      scale={0.75}   // same as old bat
      rotation-y={-Math.PI / 2}
      mass={2}
      position={[0, 3, 5.5]}
    >
      <group {...props} dispose={null} scale={0.0025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bat_Material002_0.geometry}
          material={materials['Material.002']}
          position={[-106.224, 404.266, 4.493]}
          rotation={[1.35, -0.116, 0.599]}
          scale={182.02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Handel_Material_0.geometry}
          material={materials.Material}
          position={[-240.82, 457.415, 195.268]}
          rotation={[1.35, -0.116, 0.599]}
          scale={182.02}
        />
      </group>
      <CuboidCollider args={[0.25, 1, 0.75]} />
    </RigidBody>
  )
}

useGLTF.preload('/bat.glb')
