/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 cricket_batsports.glb -s 
Author: Rohit Pawar (https://sketchfab.com/rohit8999)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cricket-batsports-d2d8e37424cb433a8f16c7f51ac5765f
Title: Cricket Bat(Sports)
*/

import React, { useRef } from 'react'
import { useGLTF ,useKeyboardControls} from '@react-three/drei'
import { CuboidCollider, RigidBody } from '@react-three/rapier'
import { useFrame } from '@react-three/fiber'

export function Model(props) {

  const { nodes, materials } = useGLTF('/cricket_batsports.glb')
  const batposition =useRef()
  const [subscribeKeys, getKeys] = useKeyboardControls()  // hook that give access to which key is pressed
  
  useFrame((state, delta) => {
    
     const { forward, backward, left, right,shift } = getKeys()  // to get which key is pressed 
     if(forward & shift){
        
        batposition.current?.applyImpulse({x:0,y:0.17,z:-0.01})
        batposition.current?.addTorque({x: 0.006,y:0,z:0})
        
     }else if(right & shift){
      batposition.current?.applyImpulse({ x: 0.0, y: 0.17, z: -0.017 })
      
      batposition.current?.addTorque({ x: 0, y: -0.01, z: 0 })
      
     }
     else if(left & shift){
      batposition.current?.applyImpulse({ x: 0.0, y: 0.17, z: -0.017 })
      
      batposition.current?.addTorque({ x: 0, y: 0.01, z: 0 })
     }
     else if(backward & shift){

     }else{
       
     }
     
  })

  return (
    <RigidBody ref={batposition} type='dynamic'  scale={0.75} colliders={false} rotation-y={-Math.PI/2}  mass={2} position={[0,3,5.5]}>
    <group {...props} dispose={null}  scale={0.0025}>
      <group position={[5.443, -10.859, 1.33]} rotation={[-Math.PI/2, Math.PI/2, -Math.PI/2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-111.666, 415.125, 3.163]} rotation={[1.35, -0.116, 0.599]} scale={182.02}>
            <mesh castShadow receiveShadow geometry={nodes.Bat_Material002_0.geometry} material={materials['Material.002']} />
            <mesh castShadow receiveShadow geometry={nodes.Handel_Material_0.geometry} material={materials.Material} position={[0.001, 1.315, 0.03]} />
          </group>
        </group>
      </group>
    </group>
    <CuboidCollider args={[0.25,1,0.75]} />
    </RigidBody>
  )
}

useGLTF.preload('/cricket_batsports.glb')
