/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 untitled1.glb -s 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { CylinderCollider, RigidBody } from '@react-three/rapier'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled1.glb')
  return (
    <RigidBody colliders='trimesh' position={[0,1,11.7]}   rotation-y={Math.PI/2} mass={2000}>
    <group {...props} dispose={null} scale={0.05}>
      <mesh castShadow receiveShadow geometry={nodes['Cylinder002_13_-_Default_0'].geometry} material={materials['13_-_Default']} position={[93.408, -1.412, 9.876]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes['Cylinder003_13_-_Default_0'].geometry} material={materials['13_-_Default']} position={[93.408, -1.393, 2.813]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes['Cylinder004_13_-_Default_0'].geometry} material={materials['13_-_Default']} position={[93.408, -1.414, 16.924]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes['Cylinder013_15_-_Default_0'].geometry} material={materials['15_-_Default']} position={[93.421, 30.877, 7.973]} rotation={[-0.004, 0, 0.108]} />
      <mesh castShadow receiveShadow geometry={nodes['Cylinder014_15_-_Default_0'].geometry} material={materials['15_-_Default']} position={[93.421, 30.824, 15.02]} rotation={[0, 0.005, -0.051]} />
    </group>
    
    </RigidBody>
  )
}

useGLTF.preload('/untitled1.glb')
