/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ball.glb -s 
Author: Rohit Pawar (https://sketchfab.com/rohit8999)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cricket-ball-sports-white-f7fb5ae0d11e4d37a2d9ebccfcba5592
Title: Cricket Ball (Sports) (White).
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF,Html } from '@react-three/drei'
import * as THREE from "three"
import { useFrame } from '@react-three/fiber'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ball.glb')
  



  return (
   <>
     
    <group  {...props} dispose={null}>
      
      <group rotation={[-2.713, 0, -0.398]} scale={0.1}>
        <group position={[0.963, -0.205, -0.003]}>
          <mesh castShadow receiveShadow geometry={nodes.Cylinder002_Material002_0.geometry} material={materials['Material.002']} />
          <mesh castShadow receiveShadow geometry={nodes.Cylinder002_Material002_0_1.geometry} material={materials['Material.002']} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.Sphere_Material004_0.geometry} material={materials['Material.004']} />
      </group>
    </group>
    </> 
  )
}

useGLTF.preload('/ball.glb')
